export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_BALANCES = 'SET_BALANCES';
export const SET_RATES = 'SET_RATES';
export const SET_NATIONAL_AMOUNT = 'SET_NATIONAL_AMOUNT';
